// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjSJcNMH05BLCAv0uOJ-2j8CX-kadElRc',
    appId: '1:807162605566:web:606a79392a77870b445aaf',
    messagingSenderId: '807162605566',
    projectId: 'hydrolink-testing',
    authDomain: 'hydrolink-testing.firebaseapp.com',
    storageBucket: 'hydrolink-testing.appspot.com',
    measurementId: 'G-S452XVVMMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLcouecDW-MWDGEUW-KFUSvRJhOirKFuw',
    appId: '1:807162605566:android:fd6b2db69d8e5e6b445aaf',
    messagingSenderId: '807162605566',
    projectId: 'hydrolink-testing',
    storageBucket: 'hydrolink-testing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqY_OCMNHriRWpo2NTzFi0ihD3N5kIuc',
    appId: '1:807162605566:ios:02380ba2f6b4f3f9445aaf',
    messagingSenderId: '807162605566',
    projectId: 'hydrolink-testing',
    storageBucket: 'hydrolink-testing.appspot.com',
    iosBundleId: 'com.example.hydrolinkTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZqY_OCMNHriRWpo2NTzFi0ihD3N5kIuc',
    appId: '1:807162605566:ios:b71d810c7849082b445aaf',
    messagingSenderId: '807162605566',
    projectId: 'hydrolink-testing',
    storageBucket: 'hydrolink-testing.appspot.com',
    iosBundleId: 'com.example.hydrolinkTesting.RunnerTests',
  );
}
